# Generated by Django 3.2 on 2021-08-05 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='記録した日付')),
                ('time', models.TimeField(blank=True, default=django.utils.timezone.now, help_text='記録した時間', null=True)),
                ('stress_1', models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50)),
                ('strespoint_1', models.CharField(blank=True, help_text='気持ちの強さ１', max_length=100)),
                ('stress_2', models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50)),
                ('strespoint_2', models.CharField(blank=True, help_text='気持ちの強さ２（あれば）', max_length=100)),
                ('think', models.CharField(blank=True, choices=[('なし', 'なし'), ('①', '①'), ('②', '②')], help_text='考えの落とし穴', max_length=100)),
                ('evidence', models.TextField(blank=True, help_text='その根拠', max_length=100)),
                ('opposite', models.TextField(blank=True, help_text='気持ち', max_length=200)),
                ('stress_3', models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50)),
                ('strespoint_3', models.CharField(blank=True, help_text='気持ちの強さ１', max_length=100)),
                ('stress_4', models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50)),
                ('strespoint_4', models.CharField(blank=True, help_text='気持ちの強さ２（あれば）', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='action',
            field=models.CharField(blank=True, help_text='行動', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='body',
            field=models.CharField(blank=True, help_text='身体感覚', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='emotion',
            field=models.CharField(blank=True, help_text='気持ち', max_length=200),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='event',
            field=models.CharField(blank=True, help_text='きっかけ', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='strespoint',
            field=models.CharField(blank=True, help_text='行動', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='stress',
            field=models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='think',
            field=models.CharField(blank=True, help_text='考え', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='time',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, help_text='時間', null=True),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point1',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point10',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point11',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point12',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point13',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point14',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point15',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point16',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point17',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point18',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point19',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point20',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point21',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point22',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point23',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point24',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point25',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point26',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point27',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point28',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point29',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point30',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point4',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point5',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point6',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point7',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point8',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='point9',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stpointmodel',
            name='sumpoint',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wordmodel',
            name='category',
            field=models.TextField(blank=True, choices=[('いつでも', 'いつでも'), ('不安', '不安'), ('恐怖', '恐怖'), ('悲しい時に送る言葉', '悲しい時に送る言葉'), ('眠っていない', '眠っていない'), ('躁度が高い', '躁度が高い'), ('躁度が低い', '躁度が低い'), ('ストレス値高い', 'ストレス値高い'), ('イライラしている', 'イライラしている'), ('焦っている', '焦っている')], verbose_name='どんな時にかけたい言葉ですか？'),
        ),
    ]
