# Generated by Django 3.2 on 2021-06-17 01:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorModel',
            fields=[
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='日付', primary_key=True, serialize=False)),
                ('event', models.CharField(help_text='きっかけ', max_length=100)),
                ('think', models.CharField(help_text='考え', max_length=100)),
                ('action', models.CharField(help_text='行動', max_length=100)),
                ('emotion', models.CharField(help_text='気持ち', max_length=200)),
                ('body', models.CharField(help_text='身体感覚', max_length=100)),
                ('stress', models.CharField(choices=[('1', '焦り'), ('2', '睡眠不足'), ('3', '生活リズム'), ('4', 'イライラ'), ('5', '他人の仕事'), ('6', '不要な共感'), ('7', '過食'), ('8', '疲れ'), ('9', '怒り'), ('10', '我慢'), ('11', '会話不足')], max_length=50)),
                ('strespoint', models.CharField(help_text='行動', max_length=100)),
            ],
        ),
    ]
