# Generated by Django 3.2 on 2021-08-05 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0002_auto_20210806_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stpointnamemodel',
            name='category',
            field=models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=20, verbose_name='分類'),
        ),
    ]
