# Generated by Django 3.2 on 2021-08-06 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_stpointnamemodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='fall',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('①', '①'), ('②', '②')], help_text='考えの落とし穴', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='think',
            field=models.TextField(blank=True, help_text='浮かんだ考え心のつぶやき', max_length=100),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='action',
            field=models.CharField(blank=True, help_text='行動', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='body',
            field=models.CharField(blank=True, help_text='身体感覚', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='emotion',
            field=models.CharField(blank=True, help_text='気持ち', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='event',
            field=models.CharField(blank=True, help_text='きっかけ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='strespoint',
            field=models.CharField(blank=True, help_text='行動', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='stress',
            field=models.CharField(blank=True, choices=[('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='think',
            field=models.CharField(blank=True, help_text='考え', max_length=100, null=True),
        ),
    ]
