# Generated by Django 3.2 on 2021-08-16 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_auto_20210806_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='srmmodel',
            name='day',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='evidence',
            field=models.TextField(blank=True, help_text='その根拠', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='fall',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('①', '①'), ('②', '②')], default='なし', help_text='考えの落とし穴', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='opposite',
            field=models.TextField(blank=True, help_text='気持ち', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='strespoint_1',
            field=models.IntegerField(blank=True, default=0, help_text='気持ちの強さ１', null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='strespoint_2',
            field=models.IntegerField(blank=True, default=0, help_text='気持ちの強さ２（あれば）', null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='strespoint_3',
            field=models.IntegerField(blank=True, default=0, help_text='気持ちの強さ１', null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='strespoint_4',
            field=models.IntegerField(blank=True, default=0, help_text='気持ちの強さ２（あれば）', null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='stress_1',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], default='なし', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='stress_2',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], default='なし', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='stress_3',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], default='なし', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='stress_4',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], default='なし', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='exercisemodel',
            name='think',
            field=models.TextField(blank=True, help_text='浮かんだ考え心のつぶやき', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='monitormodel',
            name='stress',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_time5',
            field=models.TimeField(blank=True, default=datetime.time(17, 30), help_text='帰宅の時間', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_time6',
            field=models.TimeField(blank=True, default=datetime.time(18, 30), help_text='夕食の時間', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value1',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=2, help_text='昨就寝の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value10',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='#10の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value2',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='起床の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value3',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=2, help_text='接触の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value4',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=2, help_text='集団の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value5',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=2, help_text='帰宅の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value6',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=2, help_text='夕食の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value7',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='#7の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value8',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='#8の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='srmmodel',
            name='action_value9',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, help_text='#9の活動量 0～3', null=True),
        ),
        migrations.AlterField(
            model_name='stpointnamemodel',
            name='category',
            field=models.CharField(blank=True, choices=[('なし', 'なし'), ('焦り', '焦り'), ('不安', '不安'), ('恐怖', '恐怖'), ('睡眠不足', '睡眠不足'), ('生活リズム', '生活リズム'), ('イライラ', 'イライラ'), ('他人の仕事', '他人の仕事'), ('不要な共感', '不要な共感'), ('過食', '過食'), ('疲れ', '疲れ'), ('怒り', '怒り'), ('我慢', '我慢'), ('会話不足', '会話不足')], max_length=20, verbose_name='分類'),
        ),
    ]
