# Generated by Django 3.2 on 2021-08-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_auto_20210816_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srmmodel',
            name='ivent',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
